{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  user: {{ .Values.auth.user | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
