services:
  microsocks:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-ghcr.io/fidasek009/microsocks}:${TAG:-latest}
    ports:
      - "1080:1080"
    restart: unless-stopped
